import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f9f9f9',
        marginBottom: 5,
    },
    postContainer: {
        flex: 1,
        padding: 12,
        backgroundColor: '#f9f9f9',
        marginBottom: 5,
    },
    item: {
        fontSize: 16,
        backgroundColor: '#4CAF50',
        color: '#fff',
        margin: 8,
        padding: 10,
        width: 100,
        height: 100,
        borderRadius: 10,
        textAlign: 'center',
        textAlignVertical: 'center',
        marginBottom: 5,
    },
    itemDynamic: {
        fontSize: 16,
        backgroundColor: '#2196F3',
        color: '#fff',
        margin: 8,
        padding: 10,
        width: 100,
        height: 100,
        borderRadius: 10,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    header: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#2c3e50',
        marginBottom: 20,
        textAlign: 'center',
    },
    subHeader: {
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 15,
        color: '#34495e',
        textAlign: 'left',
    },
    textInput: {
        width: '100%',
        padding: 12,
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        marginBottom: 15,
        backgroundColor: '#fff',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    button: {
        backgroundColor: '#27ae60',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    linkButton: {
        backgroundColor: '#2980b9',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginTop: 10,
    },
    linkButtonText: {
        color: '#fff',
        fontSize: 16,
        textAlign: 'center',
    },
    counterText: {
        fontSize: 26,
        marginTop: 20,
        color: '#2c3e50',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    listItem: {
        fontSize: 18,
        paddingVertical: 12,
        paddingHorizontal: 10,
        marginVertical: 6,
        marginBottom: 10,
        backgroundColor: '#ecf0f1',
        borderRadius: 6,
        color: '#2c3e50',
    },
    modalContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 30,
    },
    modalButton: {
        marginTop: 20,
        backgroundColor: '#27ae60',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
});

export default styles;
